import { useState } from 'react'
import type { DiaryPeriodResponse } from '../types'
import { formatRange } from '../lib/dates'
import { formatDateTime } from '../../../shared/lib/format'

interface Props {
  period: DiaryPeriodResponse
  onGenerate: (period: DiaryPeriodResponse) => void
  onSaveUser: (period: DiaryPeriodResponse, text: string) => void
  generating: boolean
  saving: boolean
  onClose?: () => void
}

export const PeriodSummaryPanel = ({ period, onGenerate, onSaveUser, generating, saving, onClose }: Props) => {
  // The parent keys this panel by period, so a period switch remounts it with fresh state.
  const [text, setText] = useState(period.userSummary ?? '')

  const label = period.type === 'MONTH' ? 'Итог месяца' : 'Итог недели'
  const dirty = text !== (period.userSummary ?? '')

  return (
    <div className="bg-white rounded-lg shadow p-4 space-y-4">
      <div className="flex items-start justify-between gap-2">
        <div>
          <h3 className="font-semibold text-gray-900">{label}</h3>
          <div className="text-sm text-gray-500">{formatRange(period.start, period.end)}</div>
        </div>
        {onClose && (
          <button onClick={onClose} className="text-sm text-gray-400 hover:text-gray-600">Закрыть</button>
        )}
      </div>

      <section>
        <div className="flex items-center justify-between gap-2 mb-1">
          <h4 className="text-sm font-medium text-gray-700">Автоматический итог</h4>
          <button
            onClick={() => onGenerate(period)}
            disabled={generating}
            className="text-sm px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 disabled:opacity-50"
          >
            {generating ? 'Формируется…' : period.autoSummary ? 'Обновить' : 'Сформировать'}
          </button>
        </div>
        {period.autoSummary ? (
          <>
            <div className="whitespace-pre-wrap text-sm text-gray-800 bg-gray-50 rounded p-3">{period.autoSummary}</div>
            <div className="text-xs text-gray-400 mt-1">
              {period.autoGeneratedAt ? `Сформирован ${formatDateTime(period.autoGeneratedAt)}` : ''}
              {period.autoSummaryThrough && !period.closed ? ' · по данным до ' + period.autoSummaryThrough : ''}
            </div>
          </>
        ) : (
          <p className="text-sm text-gray-500">
            {period.closed
              ? 'Итог ещё не сформирован — он появится автоматически, или нажмите «Сформировать».'
              : 'Период ещё идёт. Можно сформировать промежуточный итог по уже подведённым дням.'}
          </p>
        )}
      </section>

      <section>
        <h4 className="text-sm font-medium text-gray-700 mb-1">Своими словами</h4>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          maxLength={4000}
          rows={5}
          placeholder="Как этот период прошёл для вас? Это тоже станет частью памяти дневника."
          className="w-full border rounded-lg p-3 text-sm resize-y focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <div className="flex items-center justify-between mt-1">
          <span className="text-xs text-gray-400">{text.length} / 4000</span>
          <button
            onClick={() => onSaveUser(period, text)}
            disabled={saving || !dirty}
            className="text-sm px-4 py-1.5 rounded bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {saving ? 'Сохранение…' : 'Сохранить'}
          </button>
        </div>
      </section>
    </div>
  )
}
