package com.diplom.chatservice.dto.diary;

import java.time.LocalDate;
import java.time.OffsetDateTime;

public record DiaryPeriodResponse(
        String type,
        LocalDate start,
        LocalDate end,
        String autoSummary,
        LocalDate autoSummaryThrough,
        OffsetDateTime autoGeneratedAt,
        String userSummary,
        OffsetDateTime userUpdatedAt,
        boolean closed
) {}
