server:
  port: 8082

spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://localhost:5433/diplom_db
    username: admin
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: content_schema
  flyway:
    schemas: content_schema
    default-schema: content_schema
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
