export type DiaryRoomStatus = 'ACTIVE' | 'ARCHIVED' | 'ABANDONED' | 'EXPIRED' | string

export interface DiaryDayResponse {
  roomId: string
  date: string
  status: DiaryRoomStatus
  writable: boolean
  summary: string | null
  turnCount: number
  title: string | null
  createdAt: string
  closedAt: string | null
}

export interface DiaryCalendarDay {
  date: string
  roomId: string
  status: DiaryRoomStatus
  turnCount: number
  hasSummary: boolean
  writable: boolean
}

export type DiaryPeriodType = 'WEEK' | 'MONTH'

export interface DiaryPeriodResponse {
  type: DiaryPeriodType
  start: string
  end: string
  autoSummary: string | null
  autoSummaryThrough: string | null
  autoGeneratedAt: string | null
  userSummary: string | null
  userUpdatedAt: string | null
  closed: boolean
}

export interface DiaryCalendarResponse {
  month: string
  serverToday: string
  days: DiaryCalendarDay[]
  weeks: DiaryPeriodResponse[]
  monthPeriod: DiaryPeriodResponse
}

export type MemoryKind = 'YEAR_AGO' | 'MONTH_AGO'

export interface DiaryMemory {
  kind: MemoryKind
  date: string
  roomId: string
  summary: string | null
  turnCount: number
}

export interface DiaryMemoriesResponse {
  date: string
  items: DiaryMemory[]
}

export type MemoryFactCategory = 'PERSON' | 'THEME' | 'GOAL' | 'TRIGGER' | 'VALUE' | 'OTHER'

export interface MemoryFactResponse {
  id: string
  category: MemoryFactCategory
  content: string
  firstSeenDate: string
  lastConfirmedDate: string
}
