server:
  port: 8083

spring:
  application:
    name: chat-service
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/diplom_db
    username: admin
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: chat_schema
  flyway:
    schemas: chat_schema
    default-schema: chat_schema

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

user-service:
  base-url: http://localhost:8081

chat:
  default-ai-model: gemini-2.5-flash-lite
  llm:
    provider: openai-compatible
    base-url: https://generativelanguage.googleapis.com/v1beta/openai/
    model: gemini-2.5-flash-lite
    api-key: ${LLM_API_KEY:}
    max-output-tokens: 700
    temperature: 0.6
    request-timeout-ms: 45000
    max-retries: 2

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
