package com.diplom.chatservice.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Week (ISO Monday–Sunday) or calendar-month diary period with an automatic summary and the
 * author's own summary ("своими словами"). Both are context layers for later entries.
 */
@Entity
@Table(name = "diary_periods", schema = "chat_schema")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DiaryPeriod {

    public static final int TYPE_WEEK = 1;
    public static final int TYPE_MONTH = 2;

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "owner_user_id", nullable = false)
    private UUID ownerUserId;

    @Column(name = "period_type_id", nullable = false)
    private Integer periodTypeId;

    @Column(name = "period_start", nullable = false)
    private LocalDate periodStart;

    @Column(name = "period_end", nullable = false)
    private LocalDate periodEnd;

    @Column(name = "auto_summary", columnDefinition = "TEXT")
    private String autoSummary;

    @Column(name = "auto_summary_through")
    private LocalDate autoSummaryThrough;

    @Column(name = "auto_generated_at")
    private OffsetDateTime autoGeneratedAt;

    @Column(name = "user_summary", columnDefinition = "TEXT")
    private String userSummary;

    @Column(name = "user_updated_at")
    private OffsetDateTime userUpdatedAt;

    @Builder.Default
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Version
    @Column(nullable = false)
    private Integer version;
}
